// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20250926072832_Added TotalSpots and BookedSpots")]
    partial class AddedTotalSpotsandBookedSpots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookedSpots")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalSpots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-3333-111111111111"),
                            Description = "Intense core workout",
                            Title = "Core Blast"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-3333-222222222222"),
                            Title = "Yoga Flow"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-5555-3333-111111111111"),
                            Description = "Dance your way to strength and condition",
                            Title = "Zumba"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-6666-3333-222222222222"),
                            Title = "Circle Gym"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
