// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20250930203753_AddWorkoutFields")]
    partial class AddWorkoutFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.WorkoutEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookedSpots")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Instructor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalSpots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-3333-111111111111"),
                            BookedSpots = 5,
                            Date = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intense core workout",
                            Instructor = "Alice Smith",
                            Location = "Room A",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Core Blast",
                            TotalSpots = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-3333-222222222222"),
                            BookedSpots = 3,
                            Date = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Relaxing yoga session",
                            Instructor = "Bob Johnson",
                            Location = "Room B",
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Title = "Yoga Flow",
                            TotalSpots = 15
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-5555-3333-111111111111"),
                            BookedSpots = 0,
                            Date = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dance your way to strength and condition",
                            Instructor = "Carol Davis",
                            Location = "Room C",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Title = "Zumba",
                            TotalSpots = 30
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-6666-3333-222222222222"),
                            BookedSpots = 10,
                            Date = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full body workout",
                            Instructor = "David Wilson",
                            Location = "Room A",
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            Title = "Circle Gym",
                            TotalSpots = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
